on: [pull_request]
name: CI Pull Request
jobs:
  runBenchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable
      - uses: boa-dev/criterion-compare-action@v3
        with:
          benchName: "benchmark"
          branchName: ${{ github.base_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
